version: '3.2'


services:

    db:
        image: postgres:11.3
        shm_size: 256m       
        env_file: .env
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 30s
            retries: 3

    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 8080:80
        environment: 
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=123456

    # pgloader:
    #     image: dimitri/pgloader:latest        
    #     env_file: .env
    #     command: pgloader /data/input/data.load
    #     volumes: 
    #         - ./docker:/data/docker
    #         - ./data:/data/input

    sb:
        build: .
        environment: 
            - POSTGRESQL_URI="postgres://postgres:postgres@db:5432/cnpj" 
        volumes:
            - ./:/app
        command: /app/run.sh 