DROP TABLE IF EXISTS qualificacao_responsavel_socio;

CREATE TABLE qualificacao_responsavel_socio
(
    id smallint NOT NULL,
    texto character varying(200),
    CONSTRAINT qualificacao_responsavel_socio_pkey PRIMARY KEY (id)
);

INSERT INTO qualificacao_responsavel_socio (id, texto) VALUES
(1, 'Acionista'),
(2, 'Acionista Controlador'),
(3, 'Acionista Diretor'),
(4, 'Acionista Presidente'),
(5, 'Administrador'),
(6, 'Administradora de consórcio de Empresas ou Grupo de Empresas'),
(7, 'Comissário'),
(8, 'Conselheiro de Administração'),
(9, 'Curador'),
(10, 'Diretor'),
(11, 'Interventor'),
(12, 'Inventariante'),
(13, 'Liquidante'),
(14, 'Mãe'),
(15, 'Pai'),
(16, 'Presidente'),
(17, 'Procurador'),
(18, 'Secretário'),
(19, 'Síndico (Condomínio)'),
(20, 'Sociedade Consorciada'),
(21, 'Sociedade Filiada'),
(22, 'Sócio'),
(23, 'Sócio Capitalista'),
(24, 'Sócio Comanditado'),
(25, 'Sócio Comanditário'),
(26, 'Sócio de Indústria'),
(27, 'Sócio Residente ou Domiciliado no Exterior'),
(28, 'Sócio-Gerente'),
(29, 'Sócio ou Acionista Incapaz ou Relativamente Incapaz (exceto menor)'),
(30, 'Sócio ou Acionista Menor (Assistido/Representado)'),
(31, 'Sócio Ostensivo'),
(32, 'Tabelião'),
(33, 'Tesoureiro'),
(34, 'Titular de Empresa Individual Imobiliária'),
(35, 'Tutor'),
(36, 'Gerente-Delegado'),
(37, 'Sócio Pessoa Jurídica Domiciliado no Exterior'),
(38, 'Sócio Pessoa Física Residente ou Domiciliado no Exterior'),
(39, 'Diplomata'),
(40, 'Cônsul'),
(41, 'Representante de Organização Internacional'),
(42, 'Oficial de Registro'),
(43, 'Responsável'),
(44, 'Sócio Participante'),
(45, 'Sócio Investidor'),
(46, 'Ministro de Estado das Relações Exteriores'),
(47, 'Sócio Pessoa Física Residente no Brasil'),
(48, 'Sócio Pessoa Jurídica Domiciliado no Brasil'),
(49, 'Sócio-Administrador'),
(50, 'Empresário'),
(51, 'Candidato a Cargo Político Eletivo'),
(52, 'Sócio com Capital'),
(53, 'Sócio sem Capital'),
(54, 'Fundador'),
(55, 'Sócio Comanditado Residente no Exterior'),
(56, 'Sócio Comanditário Pessoa Física Residente no Exterior'),
(57, 'Sócio Comanditário Pessoa Jurídica Domiciliado no Exterior'),
(58, 'Sócio Comanditário Incapaz'),
(59, 'Produtor Rural'),
(60, 'Cônsul Honorário'),
(61, 'Responsável Indigena'),
(62, 'Representante das Instituições Extraterritoriais'),
(63, 'Cotas em Tesouraria'),
(64, 'Administrador Judicial'),
(65, 'Titular Pessoa Física Residente ou Domiciliado no Brasil'),
(66, 'Titular Pessoa Física Residente ou Domiciliado no Exterior'),
(67, 'Titular Pessoa Física Incapaz ou Relativamente Incapaz (exceto menor)'),
(68, 'Titular Pessoa Física Menor (Assistido/Representado)'),
(69, 'Beneficiário Final'),
(70, 'Administrador Residente ou Domiciliado no Exterior'),
(71, 'Conselheiro de Administração Residente ou Domiciliado no Exterior'),
(72, 'Diretor Residente ou Domiciliado no Exterior'),
(73, 'Presidente Residente ou Domiciliado no Exterior'),
(74, 'Sócio-Administrador Residente ou Domiciliado no Exterior'),
(75, 'Fundador Residente ou Domiciliado no Exterior'),
(76, 'Protetor'),
(77, 'Vice-Presidente'),
(78, 'Titular Pessoa Jurídica Domiciliada no Brasil'),
(79, 'Titular Pessoa Jurídica Domiciliada no Exterior');


CREATE TABLE motivo_situacao_cadastral
(
    id smallint NOT NULL,
    texto character varying(200),
    CONSTRAINT motivo_situacao_cadastral_pkey PRIMARY KEY (id)
);

INSERT INTO motivo_situacao_cadastral (id, texto) VALUES
(1,'EXTINÇÃO POR ENCERRAMENTO LIQUIDAÇÃO VOLUNTÁRIA'),
(2,'INCORPORAÇÃO'),
(3,'FUSÃO'),
(4,'CISÃO TOTAL '),
(5,'ENCERRAMENTO DA FALÊNCIA'),
(6,'ENCERRAMENTO DA LIQUIDAÇÃO'),
(7,'ELEVAÇÃO A MATRIZ'),
(8,'TRANSPASSE '),
(9,'NÃO INÍCIO DE ATIVIDADE'),
(10,'EXTINÇÃO PELO ENCERRAMENTO DA LIQUIDAÇÃO JUDICIAL'),
(11,'ANULAÇÃO POR MULTICIPLIDADE'),
(12,'ANULAÇÃO ONLINE DE OFICIO'),
(13,'OMISSA CONTUMAZ'),
(14,'OMISSA NÃO LOCALIZADA'),
(15,'INEXISTENTE DE FATO'),
(16,'ANULAÇÃO POR VÍCIOS'),
(17,'BAIXA INICIADA E AINDA NÃO DEFERIDA'),
(18,'INTERRUPÇÃO TEMPORÁRIA DAS ATIVIDADES'),
(19,'OMISSO DE DIRPJ ATÉ 5 EXERCÍCIOS'),
(20,'EM CONDIÇÃO DE INAPTIDÃO'),
(21,'PEDIDO DE BAIXA INDEFERIDA'),
(22,'RESTABELECIMENTO COM CERTIDÃO POSITIVA COM EFEITO DE NEGATIVA'),
(23,'COM PENDÊNCIA FISCAL'),
(24,'POR EMISSÃO CERTIDÃO NEGATIVA'),
(25,'CERTIDÃO POSITIVA COM EFEITO DE NEGATIVA'),
(26,'IRREGULARIDADE DE PAGAMENTO'),
(27,'IRREGULARIDADE DE RECOLHIMENTO E EXIGIBILIDADE SUSPENSA'),
(28,'TRANSFERÊNCIA FILIAL CONDIÇÃO MATRIZ'),
(29,'AGUARDANDO CONF. DE DIRPJ/DIPJ'),
(30,'ANR - AGUARDANDO CONF. DE DIRPJ/DIPJ'),
(31,'EXTINÇÃO DA FILIAL'),
(32,'INEXISTENTE DE FATO – ADE/COSAR'),
(33,'TRANSFERÊNCIA DO ÓRGÃO LOCAL A CONDIÇÃO DE FILIAL DO ÓRGÃO REGIONAL'),
(34,'ANULAÇÃO DE INSCRIÇÃO INDEVIDA'),
(35,'EMPRESA ESTRANGEIRA AGUARDANDO DOCUMENTAÇÃO'),
(36,'PRÁTICA IRREGULAR DE OPERAÇÃO DE COMERCIO EXTERIOR'),
(37,'BAIXA DE PRODUTOR RURAL'),
(38,'BAIXA DEFERIDA PELA RFB AGUARDANDO ANALISE DO CONVENENTE'),
(39,'BAIXA DEFERIDA PELA RFB E INDEFERIDA PELO CONVENENTE'),
(40,'BAIXA INDEFERIDA PELA RFB E AGUARDANDO ANALISE DO CONVENENTE'),
(41,'BAIXA INDEFERIDA PELA RFB E DEFERIDA PELO CONVENENTE'),
(42,'BAIXA INDEFERIDA PELA RFB E SEFIN, AGUARDANDO ANALISE SEFAZ'),
(43,'BAIXA DEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFAZ E INDEFERIDA PELA SEFIN'),
(44,'BAIXA DEFERIDA PELA RFB E SEFAZ, AGUARDANDO ANALISE SEFIN'),
(45,'BAIXA DEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFIN E INDEFERIDA PELA SEFAZ'),
(46,'BAIXA DEFERIDA PELA RFB E SEFAZ E INDEFERIDA PELA SEFIN'),
(47,'BAIXA DEFERIDA PELA RFB E SEFIN E INDEFERIDA PELA SEFAZ'),
(48,'BAIXA INDEFERIDA PELA RFB, AGUARDANDO ANALISE SEFAZ E DEFERIDA PELA SEFIN'),
(49,'BAIXA INDEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFAZ E INDEFERIDA PELA SEFIN'),
(50,'BAIXA INDEFERIDA PELA RFB, DEFERIDA PELA SEFAZ E AGUARDANDO ANALISE DA SEFIN'),
(51,'BAIXA INDEFERIDA PELA RFB E SEFAZ, AGUARDANDO ANALISE DA SEFIN'),
(52,'BAIXA INDEFERIDA PELA RFB, DEFERIDA PELA SEFAZ E INDEFERIDA PELA SEFIN'),
(53,'BAIXA INDEFERIDA PELA RFB E SEFAZ E DEFERIDA PELA SEFIN'),
(54,'BAIXA - TRATAMENTO DIFERENCIADO DADO AS ME E EPP (LEI COMPLEMENTAR NUMERO 123/2006)'),
(55,'DEFERIDO PELO CONVENENTE, AGUARDANDO ANALISE DA RFB'),
(60,'ARTIGO 30, VI, DA IN 748/2007'),
(61,'INDICIO INTERPOS. FRAUDULENTA'),
(62,'FALTA DE PLURALIDADE DE SOCIOS'),
(63,'OMISSÃO DE DECLARAÇÕES'),
(64,'LOCALIZAÇÃO DESCONHECIDA'),
(66,'INAPTIDÃO'),
(67,'REGISTRO CANCELADO'),
(70,'ANULAÇÃO POR NÃO CONFIRMADO ATO DE REGISTRO DO MEI NA JUNTA COMERCIAL'),
(71,'INAPTIDÃO (LEI 11.941/2009 ART.54)'),
(72,'DETERMINAÇÃO JUDICIAL'),
(73,'OMISSÃO CONTUMAZ'),
(74,'INCONSISTÊNCIA CADASTRAL'),
(80,'BAIXA REGISTRADA NA JUNTA, INDEFERIDA NA RFB');
